### ISSUE TITLE
Updates to Website 

### ISSUE THREAD

**Issue by G-Accad** [SheffieldR/SheffieldR.github.io#59]
- [x] Update twitter icon to X 
- [x] Add slack icon 
- [x] Combine Resources and Slides 
- [x] Add all icons to the bottom of the pages
- [x] Confirm if the xml RSS should be in each page or only at the top bar
- [x] Link the meetup page at the top or in events/about
                    options for icon: people, chat, calendar, geo, geo-alt

**Comment by ns-rse** [comment]
> Confirm if the xml RSS should be in each page or only at the top bar

Its not needed in each page and is fine in the header, new posts get incrementally included in the linked `index.xml` that the icon links to.

**Comment by G-Accad** [comment]
New suggestions:

- [x] switch RSS and mastodon at the top bar
- [x] remove all links to SheffieldR twitter
- [x] remove links to all accounts at the bottom of pages
- [x] change the names in the R ladies page from Github --> RLadies Github (to distinguish between the two accounts) 
- [x] Add RLadies Meet up link
